'use strict';
/**
 * CoreSystem Workspace — Code Generator
 * Converts the spatial layout into production HTML5 + ITCSS CSS + minimal JS.
 * Also handles ZIP download.
 */
const CodeGen = (() => {

  // ── Helpers ───────────────────────────────────────────────────────────────
  function _px(v)  { return `${Math.round(v)}px`; }
  function _rgba(hex, alpha) {
    if (!hex || hex === 'transparent') return 'transparent';
    if (alpha === 1 || alpha === undefined) return hex;
    const r = parseInt(hex.slice(1,3),16), g = parseInt(hex.slice(3,5),16), b = parseInt(hex.slice(5,7),16);
    return `rgba(${r},${g},${b},${alpha})`;
  }
  function _indent(n) { return '  '.repeat(n); }

  // ── HTML generation ───────────────────────────────────────────────────────
  function _htmlNode(node, depth) {
    const i  = _indent(depth);
    const i2 = _indent(depth + 1);
    const tag = node.htmlTag || 'div';
    const cls = node.cssClass ? ` class="${node.cssClass}"` : '';
    const aria = _aria(node);

    const inner = node.children.length
      ? '\n' + node.children.map(c => _htmlNode(c, depth+1)).join('\n') + '\n' + i
      : _placeholder(node);

    return `${i}<${tag}${cls}${aria}>${inner}</${tag}>`;
  }

  function _aria(node) {
    switch (node.role) {
      case 'header':       return ' role="banner"';
      case 'footer':       return ' role="contentinfo"';
      case 'sidebar-left':
      case 'sidebar-right':return ' aria-label="Sidebar"';
      case 'nav':          return ' aria-label="Main navigation"';
      default:             return '';
    }
  }

  function _placeholder(node) {
    switch (node.role) {
      case 'header':  return `\n    <a href="/" class="logo">Logo</a>\n    <nav><a href="#">Home</a> <a href="#">About</a> <a href="#">Contact</a></nav>\n  `;
      case 'nav':     return `\n    <a href="/" class="logo">Brand</a>\n    <ul><li><a href="#">Home</a></li><li><a href="#">About</a></li><li><a href="#">Contact</a></li></ul>\n    <button class="nav-toggle" aria-label="Toggle menu">☰</button>\n  `;
      case 'hero':    return `\n    <h1>Your Headline Here</h1>\n    <p>A compelling subheadline that explains your value proposition.</p>\n    <a href="#" class="btn-primary">Get Started</a>\n  `;
      case 'footer':  return `\n    <p>&copy; ${new Date().getFullYear()} Your Company. All rights reserved.</p>\n  `;
      case 'card':    return `\n    <h3>${node.el.name}</h3>\n    <p>Card description goes here.</p>\n    <a href="#">Learn more →</a>\n  `;
      case 'sidebar-left':
      case 'sidebar-right': return `\n    <h2>Sidebar</h2>\n    <ul><li><a href="#">Link 1</a></li><li><a href="#">Link 2</a></li></ul>\n  `;
      default:        return `\n    <!-- ${node.el.name} content -->\n  `;
    }
  }

  function generateHTML(tree) {
    const bodyLines = (tree.roots || []).map(n => _htmlNode(n, 1)).join('\n');
    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="Generated by CoreSystem Visual Workspace">
  <title>Layout</title>
  <link rel="stylesheet" href="styles.css">
</head>
<body>
${bodyLines}
  <script src="script.js"><\/script>
</body>
</html>`;
  }

  // ── CSS generation ────────────────────────────────────────────────────────
  function _elCSS(node, parentNode) {
    const el  = node.el;
    const cls = node.cssClass || `el-${el.id}`;
    const isTopLevel = !parentNode;
    const parentLayout = parentNode ? (parentNode.layout || 'block') : 'absolute';

    const rules = [];

    // Positioning strategy
    if (isTopLevel || parentLayout === 'absolute') {
      rules.push(`position:absolute;`);
      rules.push(`left:${_px(el.x)};`);
      rules.push(`top:${_px(el.y)};`);
    }
    rules.push(`width:${_px(el.width)};`);
    rules.push(`height:${_px(el.height)};`);

    if (el.fill && el.fill !== '#FFFFFF') {
      rules.push(`background-color:${_rgba(el.fill, el.opacity)};`);
    }
    if (el.strokeWidth > 0 && el.stroke) {
      rules.push(`border:${el.strokeWidth}px solid ${el.stroke};`);
    }
    if (el.borderRadius > 0) {
      rules.push(`border-radius:${_px(el.borderRadius)};`);
    }
    if (el.opacity < 1) {
      rules.push(`opacity:${el.opacity};`);
    }

    // Layout
    switch (node.layout) {
      case 'flex-row':
        rules.push(`display:flex;`, `flex-direction:row;`, `flex-wrap:wrap;`, `gap:${el.gap || 16}px;`);
        break;
      case 'flex-col':
        rules.push(`display:flex;`, `flex-direction:column;`, `gap:${el.gap || 16}px;`);
        break;
      case 'grid': {
        const cols = Math.max(1, el.gridCols || Math.round(el.width / 260));
        rules.push(`display:grid;`, `grid-template-columns:repeat(${cols},1fr);`, `gap:${el.gap || 16}px;`);
        break;
      }
    }

    return `.${cls} {\n${rules.map(r => '  '+r).join('\n')}\n}`;
  }

  function generateCSS(tree) {
    const sections = [];

    // 1. Design tokens
    sections.push(`/* ====================================================
   1. Design Tokens
   ==================================================== */
:root {
  --color-primary: #3B82F6;
  --color-secondary: #6366F1;
  --color-text: #1E293B;
  --color-bg: #FFFFFF;
  --color-surface: #F8FAFC;
  --color-border: #E2E8F0;
  --font-base: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
  --font-mono: 'Cascadia Code', 'Fira Code', Consolas, monospace;
  --space-xs: 0.25rem;
  --space-sm: 0.5rem;
  --space-md: 1rem;
  --space-lg: 1.5rem;
  --space-xl: 2rem;
  --space-2xl: 3rem;
  --radius-sm: 4px;
  --radius-md: 8px;
  --radius-lg: 16px;
  --shadow-sm: 0 1px 3px rgba(0,0,0,.1);
  --shadow-md: 0 4px 12px rgba(0,0,0,.12);
  --shadow-lg: 0 8px 32px rgba(0,0,0,.16);
}`);

    // 2. Reset
    sections.push(`/* ====================================================
   2. Reset
   ==================================================== */
*, *::before, *::after { box-sizing:border-box; margin:0; padding:0; }
html { font-size:16px; scroll-behavior:smooth; }
body { font-family:var(--font-base); color:var(--color-text); background:var(--color-bg); line-height:1.6; }
img, video { max-width:100%; height:auto; display:block; }
a { color:var(--color-primary); text-decoration:none; }
a:hover { text-decoration:underline; }
ul, ol { list-style:none; }
button { cursor:pointer; border:none; background:none; font:inherit; }`);

    // 3. Layout container
    sections.push(`/* ====================================================
   3. Layout
   ==================================================== */
.layout-root {
  position:relative;
  width:${_px(State.artW)};
  min-height:${_px(State.artH)};
  margin:0 auto;
  overflow:hidden;
}
.btn-primary {
  display:inline-block;
  padding:.75rem 1.5rem;
  background:var(--color-primary);
  color:#fff;
  border-radius:var(--radius-md);
  font-weight:600;
  transition:background .2s;
}
.btn-primary:hover { background:var(--color-secondary); text-decoration:none; }
.nav-toggle { display:none; font-size:1.5rem; }`);

    // 4. Elements
    sections.push(`/* ====================================================
   4. Elements
   ==================================================== */`);
    function walkCSS(node, parentNode) {
      sections.push(_elCSS(node, parentNode));
      node.children.forEach(c => walkCSS(c, node));
    }
    (tree.roots || []).forEach(n => walkCSS(n, null));

    // 5. Responsive
    const responsive = ResponsiveEng.generate(tree);
    if (responsive) {
      sections.push(`/* ====================================================
   5. Responsive
   ==================================================== */
${responsive}`);
    }

    return sections.join('\n\n');
  }

  // ── JS generation ─────────────────────────────────────────────────────────
  function generateJS(tree) {
    const allNodes = [];
    function collect(n) { allNodes.push(n); n.children.forEach(collect); }
    (tree.roots || []).forEach(collect);

    const hasNav      = allNodes.some(n => n.role === 'nav' || n.role === 'header');
    const hasCarousel = allNodes.some(n => n.el.type === 'carousel');
    const hasFAQ      = allNodes.some(n => n.el.type === 'faq');

    if (!hasNav && !hasCarousel && !hasFAQ) return '';

    const parts = [`'use strict';\ndocument.addEventListener('DOMContentLoaded', () => {`];

    if (hasNav) {
      parts.push(`
  // Mobile navigation toggle
  const toggle = document.querySelector('.nav-toggle');
  const navList = document.querySelector('.site-nav ul, .site-header nav');
  if (toggle && navList) {
    toggle.addEventListener('click', () => {
      navList.classList.toggle('is-open');
      toggle.textContent = navList.classList.contains('is-open') ? '✕' : '☰';
    });
  }`);
    }

    if (hasCarousel) {
      parts.push(`
  // Carousel scroll
  document.querySelectorAll('.carousel').forEach(car => {
    const prev = car.querySelector('[data-prev]');
    const next = car.querySelector('[data-next]');
    if (prev) prev.addEventListener('click', () => car.scrollBy({ left:-300, behavior:'smooth' }));
    if (next) next.addEventListener('click', () => car.scrollBy({ left:300,  behavior:'smooth' }));
  });`);
    }

    if (hasFAQ) {
      parts.push(`
  // FAQ accordion
  document.querySelectorAll('.faq summary').forEach(s => {
    s.addEventListener('click', e => {
      document.querySelectorAll('.faq details[open]').forEach(d => {
        if (d !== s.parentElement) d.removeAttribute('open');
      });
    });
  });`);
    }

    parts.push(`\n});`);
    return parts.join('');
  }

  // ── Master generate ───────────────────────────────────────────────────────
  function generate() {
    const tree = Analyzer.analyze();
    return {
      html: generateHTML(tree),
      css:  generateCSS(tree),
      js:   generateJS(tree),
      tree,
    };
  }

  // ── Preview HTML (self-contained) ─────────────────────────────────────────
  function generatePreview() {
    const { html, css, js, tree } = generate();
    return html
      .replace('<link rel="stylesheet" href="styles.css">', `<style>${css}</style>`)
      .replace('<script src="script.js"></script>', js ? `<script>${js}<\/script>` : '');
  }

  // ── ZIP download ──────────────────────────────────────────────────────────
  function downloadZip(projectName = 'my-layout') {
    const { html, css, js } = generate();
    const files = {
      'index.html': html,
      'styles.css':  css,
      ...(js ? { 'script.js': js } : {}),
      'README.md': `# ${projectName}\nGenerated by CoreSystem Visual Workspace\n\n## Files\n- index.html — Semantic HTML5 structure\n- styles.css — ITCSS CSS with design tokens\n${js ? '- script.js — Minimal vanilla JS\n' : ''}\n## Usage\nOpen index.html in a browser, or serve with any static server.\n`,
    };

    const zip  = _buildZip(files);
    const blob = new Blob([zip], { type: 'application/zip' });
    const url  = URL.createObjectURL(blob);
    const a    = Object.assign(document.createElement('a'), { href: url, download: `${projectName}.zip` });
    a.click();
    setTimeout(() => URL.revokeObjectURL(url), 2000);
  }

  // ── Minimal PKZIP Store writer ────────────────────────────────────────────
  function _buildZip(files) {
    const enc = new TextEncoder();
    const u16 = v => [v & 0xFF, (v>>8) & 0xFF];
    const u32 = v => [v & 0xFF, (v>>8) & 0xFF, (v>>16) & 0xFF, (v>>24) & 0xFF];
    function crc32(data) {
      let c = 0xFFFFFFFF;
      for (let i = 0; i < data.length; i++) {
        c ^= data[i];
        for (let j = 0; j < 8; j++) c = (c >>> 1) ^ (c & 1 ? 0xEDB88320 : 0);
      }
      return (c ^ 0xFFFFFFFF) >>> 0;
    }
    const local = [], central = [];
    let offset = 0;
    const now = new Date();
    const dosDate = ((now.getFullYear()-1980)<<9)|((now.getMonth()+1)<<5)|now.getDate();
    const dosTime = (now.getHours()<<11)|(now.getMinutes()<<5)|(now.getSeconds()>>1);

    for (const [name, content] of Object.entries(files)) {
      const data  = enc.encode(content);
      const nameB = enc.encode(name);
      const crc   = crc32(data);
      const lh = [0x50,0x4B,0x03,0x04,
        ...u16(20),...u16(0),...u16(0),...u16(dosTime),...u16(dosDate),
        ...u32(crc),...u32(data.length),...u32(data.length),
        ...u16(nameB.length),...u16(0),...nameB];
      central.push([0x50,0x4B,0x01,0x02,
        ...u16(20),...u16(20),...u16(0),...u16(0),...u16(dosTime),...u16(dosDate),
        ...u32(crc),...u32(data.length),...u32(data.length),
        ...u16(nameB.length),...u16(0),...u16(0),...u16(0),...u16(0),...u32(0),...u32(offset),
        ...nameB]);
      local.push([...lh,...data]);
      offset += lh.length + data.length;
    }
    const flatLocal   = local.flat();
    const flatCentral = central.flat();
    const eocd = [0x50,0x4B,0x05,0x06,
      ...u16(0),...u16(0),...u16(central.length),...u16(central.length),
      ...u32(flatCentral.length),...u32(flatLocal.length),...u16(0)];
    return new Uint8Array([...flatLocal,...flatCentral,...eocd]);
  }

  return { generate, generateHTML, generateCSS, generateJS, generatePreview, downloadZip };
})();
